# Generates OfficialSubjectDifficultyByGrade.generated.cs from rasp.md
# Run: python tools/generate_grade_difficulties.py

import re
from pathlib import Path
from collections import Counter, defaultdict

ROOT = Path(__file__).resolve().parents[1]
RASP = ROOT / "rasp.md"
OUT = ROOT / "src" / "ArmZavuch" / "Data" / "OfficialSubjectDifficultyByGrade.generated.cs"

SKIP_SUBJECTS = {
    "Предмет", "Балл", "Col1", "Col2", "Col4", "Col6", "Col8", "Col10", "Col12",
    "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота",
}
DAY_NAMES = SKIP_SUBJECTS & {"Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"}


def parse_grades(header_line: str) -> list[int]:
    grades = []
    for m in re.finditer(r"(\d{1,2})\s*класс", header_line, re.I):
        g = int(m.group(1))
        if g not in grades:
            grades.append(g)
    return grades


def parse_row_pairs(cells: list[str], grade_count: int) -> list[tuple[str, int] | None]:
    # skip leading day / lesson columns
    idx = 0
    if idx < len(cells) and cells[idx] == "":
        idx += 1
    if idx < len(cells) and cells[idx] in DAY_NAMES:
        idx += 1
    if idx < len(cells) and re.fullmatch(r"\d{1,2}", cells[idx] or ""):
        idx += 1

    pairs: list[tuple[str, int] | None] = []
    for _ in range(grade_count):
        if idx + 1 >= len(cells):
            pairs.append(None)
            continue
        sub = cells[idx].strip()
        sc = cells[idx + 1].strip()
        idx += 2
        if not sub or not sc.isdigit():
            pairs.append(None)
            continue
        if sub.startswith("Col") or sub in SKIP_SUBJECTS:
            pairs.append(None)
            continue
        if "Разговоры о важном" in sub or "Россия" in sub and "горизонт" in sub:
            pairs.append(None)
            continue
        pairs.append((" ".join(sub.split()), int(sc)))
    return pairs


def extract_from_tables(text: str) -> dict[tuple[int, str], Counter]:
    data: dict[tuple[int, str], Counter] = defaultdict(Counter)
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i]
        if "|" in line and re.search(r"\d{1,2}\s*класс", line, re.I) and "Предмет" not in line:
            grades = parse_grades(line)
            if grades:
                i += 1
                # skip separator and subject header
                while i < len(lines) and ("Предмет" in lines[i] or re.match(r"^\|[-—]", lines[i])):
                    i += 1
                while i < len(lines):
                    row = lines[i]
                    if not row.strip().startswith("|"):
                        break
                    if "Примечание" in row or row.strip().startswith("-----"):
                        break
                    if "Итого баллов" in row:
                        i += 1
                        continue
                    cells = [c.strip() for c in row.split("|")]
                    if cells and cells[0] == "":
                        cells = cells[1:]
                    if cells and cells[-1] == "":
                        cells = cells[:-1]
                    pairs = parse_row_pairs(cells, len(grades))
                    for gi, grade in enumerate(grades):
                        if gi >= len(pairs) or pairs[gi] is None:
                            continue
                        sub, sc = pairs[gi]
                        data[(grade, sub)][sc] += 1
                    i += 1
                continue
        i += 1
    return data


def mode_score(counter: Counter) -> int:
    return counter.most_common(1)[0][0]


def main():
    text = RASP.read_text(encoding="utf-8")
    raw = extract_from_tables(text)
    by_grade: dict[int, dict[str, int]] = defaultdict(dict)
    for (grade, sub), counter in raw.items():
        by_grade[grade][sub] = mode_score(counter)

    lines = [
        "// <auto-generated by tools/generate_grade_difficulties.py — do not edit>",
        "namespace ArmZavuch.Data;",
        "",
        "public static partial class OfficialSubjectDifficultyReference",
        "{",
        "    private static partial void RegisterGradeScores()",
        "    {",
    ]
    for grade in sorted(by_grade):
        for sub in sorted(by_grade[grade], key=str.casefold):
            sc = by_grade[grade][sub]
            esc = sub.replace("\\", "\\\\").replace("\"", "\\\"")
            lines.append(f'        SetGrade({grade}, "{esc}", {sc});')
    lines.extend(["    }", "}"])
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} — {sum(len(v) for v in by_grade.values())} entries, grades {sorted(by_grade)}")


if __name__ == "__main__":
    main()
